// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtP_ya1h5SmJH1OqW4tcYhPoEM0vY3jtA',
    appId: '1:901401197938:web:0b15e34a773dc1d38ab1eb',
    messagingSenderId: '901401197938',
    projectId: 'cm10313-pi-system',
    authDomain: 'cm10313-pi-system.firebaseapp.com',
    databaseURL: 'https://cm10313-pi-system-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cm10313-pi-system.appspot.com',
    measurementId: 'G-MQGFB10LNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs9QAWMpRdN0wiu6SaPcfjDBuVuDu7a4E',
    appId: '1:901401197938:android:ca5dcb60128b494b8ab1eb',
    messagingSenderId: '901401197938',
    projectId: 'cm10313-pi-system',
    databaseURL: 'https://cm10313-pi-system-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cm10313-pi-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsl4zkzExC4hHrYa-lKGiDRyKa8lG9Tzk',
    appId: '1:901401197938:ios:b8986aeb63d8ec248ab1eb',
    messagingSenderId: '901401197938',
    projectId: 'cm10313-pi-system',
    databaseURL: 'https://cm10313-pi-system-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cm10313-pi-system.appspot.com',
    iosClientId: '901401197938-kega1cd1nojnoi99227fmatqfovljpmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsl4zkzExC4hHrYa-lKGiDRyKa8lG9Tzk',
    appId: '1:901401197938:ios:b8986aeb63d8ec248ab1eb',
    messagingSenderId: '901401197938',
    projectId: 'cm10313-pi-system',
    databaseURL: 'https://cm10313-pi-system-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cm10313-pi-system.appspot.com',
    iosClientId: '901401197938-kega1cd1nojnoi99227fmatqfovljpmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirst',
  );
}
